function relativeJointVelocities = getRelativeJointVelocities(dq1,dq2,dq3,dq4,dq5)
%GETRELATIVEJOINTVELOCITIES
%    RELATIVEJOINTVELOCITIES = GETRELATIVEJOINTVELOCITIES(DQ1,DQ2,DQ3,DQ4,DQ5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    21-Jun-2021 14:24:54

t2 = -dq3;
relativeJointVelocities = [dq1;dq1-dq2;dq2+t2;dq4+t2;-dq4+dq5];
