function relativeJointPositions = getRelativeJointPositions(q1,q2,q3,q4,q5)
%GETRELATIVEJOINTPOSITIONS
%    RELATIVEJOINTPOSITIONS = GETRELATIVEJOINTPOSITIONS(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    09-Jul-2021 12:26:41

t2 = -q3;
relativeJointPositions = [q1;q1-q2;q2+t2;q4+t2;-q4+q5];
